project:
  type: book
  output-dir: _book

book:
  title: "Computational Bioengineering"
  author:
    - name: Matthias Függer
    - name: Thomas Nowak
  date: "2026"
  chapters:
    - index.qmd
    - 01-intro/course.ipynb
    - part: "Preliminaries"
      chapters:
        - 01-intro/coding.ipynb
        - 01-intro/math.ipynb
        - 01-intro/cs.ipynb
    - part: "Introduction"
      chapters:
      - 01-intro/notes.ipynb
      - 02-intro/notes.ipynb
    - part: "Modeling"
      chapters:
      - 03-modeling/abstraction.ipynb
      - 03-modeling/quantum.ipynb
      - 03-modeling/crn.ipynb
      - 03-modeling/molecular.ipynb
      - 03-modeling/stochastic_simulation.ipynb
      - 03-modeling/mobspy.ipynb
    - part: "Distributed Algorithms"
    - part: "Nucleic Acid Design"
    - part: "Plasmid Design"
      chapters:
      - 06-plasmid/notes.ipynb
    - part: "Digital Design"
    - part: "Bulk Measurements"
      chapters:
      - 08-measure-bulk/od.ipynb
      - 08-measure-bulk/spectra.ipynb
    - part: "Cell Measurements"
      chapters:
      - 09-measure-cell/basics.ipynb
      - 09-measure-cell/ai.ipynb


from: markdown+lists_without_preceding_blankline

format:
  html:
    theme: cosmo
    css: custom.css
    code-fold: true
    code-tools: true
    fig-cap-location: margin
    toc: false
    number-sections: false
    grid:
      sidebar-width: 250px
      body-width: 800px
      margin-width: 250px
      gutter-width: 1.5em

execute:
  freeze: auto
  enabled: false
