project:
  type: book
  output-dir: _book

book:
  title: "Computational Bioengineering"
  author:
    - name: Matthias Függer
    - name: Thomas Nowak
  date: "2026"
  chapters:
    - index.qmd
    - 01-intro/course.ipynb
    - part: "Preliminaries"
      chapters:
        - 01-intro/coding.ipynb
        - 01-intro/math.ipynb
        - 01-intro/cs.ipynb
    - 01-intro/notes.ipynb
    - 02-intro/notes.ipynb

from: markdown+lists_without_preceding_blankline

format:
  html:
    theme: cosmo
    code-fold: true
    code-tools: true
    fig-cap-location: margin
    toc: false
    number-sections: false

execute:
  freeze: auto
  enabled: false
